package vista;

import controlador.ControladorIngreso;
import static controlador.ControladorIngreso.vistaIngreso;
import controlador.ControladorListado;
import controlador.ControladorLugares;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
//import java.awt.event.*;

public class VistaIngreso extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso
     */
    public VistaIngreso() {
        initComponents();
        aparienciaInicial();
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("icono/images.png"));
        this.setIconImage(ico);
    }

    public void aparienciaInicial() {
        labelDatoParticular.setVisible(false);
        datoParticular.setVisible(false);
        labelError.setVisible(false);
        jPanel2.setSize(454, 143);
//        errorLugar.setVisible(false);
//        labelError.setVisible(false);
        if (lugarTxt.getText().equals("")) {
            lugarTxt.setText("Elegir...");
        }
    }

    public void actualizarLugar(String lugar) {
        lugarTxt.setText(lugar);
        System.out.println(lugar);
    }

    public void VaciarTextFields() {
        patente.setText("");
        datoParticular.setText("");
        lugarTxt.setText("Elegir...");
        tipoVehiculo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lugarTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelDatoParticular = new javax.swing.JLabel();
        patente = new javax.swing.JTextField();
        tipoVehiculo = new javax.swing.JComboBox<>();
        datoParticular = new javax.swing.JTextField();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lugarTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(18, 59, 102));
        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ingreso de Vehículo");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 59, 102), 2, true));
        jLabel6.setOpaque(true);

        aceptar.setBackground(new java.awt.Color(23, 41, 224));
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(18, 59, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Seleccionar Lugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Lugar: ");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese los datos del vehículo"));

        jLabel1.setText("Patente");

        jLabel3.setText("Tipo de Vehículo");

        labelDatoParticular.setText("Nro de Puertas");

        patente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 59, 102), 2, true));
        patente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patenteActionPerformed(evt);
            }
        });

        tipoVehiculo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir opción...", "Auto", "Moto", "Camioneta" }));
        tipoVehiculo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 59, 102), 2, true));
        tipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVehiculoActionPerformed(evt);
            }
        });

        datoParticular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 59, 102), 2, true));
        datoParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoParticularActionPerformed(evt);
            }
        });
        datoParticular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datoParticularKeyPressed(evt);
            }
        });

        labelError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 0, 0));
        labelError.setText("Opción no seleccionada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDatoParticular))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(datoParticular, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoVehiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, 164, Short.MAX_VALUE)
                            .addComponent(patente))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelError)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(patente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datoParticular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDatoParticular))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(lugarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lugarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datoParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoParticularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datoParticularActionPerformed

    private void tipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVehiculoActionPerformed

        switch (tipoVehiculo.getSelectedItem().toString()) {
            case "Auto":
                labelDatoParticular.setText("Cantidad de Puertas");
                break;
            case "Moto":
                labelDatoParticular.setText("Cilindradas");
                break;
            case "Camioneta":
                labelDatoParticular.setText("Cabina");
                break;
        }
        datoParticular.setVisible(true);
        labelDatoParticular.setVisible(true);
    }//GEN-LAST:event_tipoVehiculoActionPerformed

    private void patenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patenteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaLugares ventanaLugares = new VistaLugares();
        ventanaLugares.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed

        //        if(Integer.parseInt(numeroLugar.getText()) <= 30){
        //             ControladorIngreso.ingresoVehiculo(patente.getText(), Integer.parseInt(numeroLugar.getText()), tipoVehiculo.getSelectedItem().toString(), datoParticular.getText());
        //             ControladorListado.actualizarLista();
        //        }else{
        //            errorLugar.setVisible(true);
        //        }
        
        if (tipoVehiculo.getSelectedItem().toString().equals("Elegir opción...")) {
            labelError.setVisible(true);
        } else if (lugarTxt.getText().toString().equals("Elegir...")) {
            JOptionPane.showMessageDialog(vistaIngreso, "Elija un lugar para el vehículo");
        } else if (patente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(vistaIngreso, "Ingrese una patente");
        } else if (datoParticular.getText().isEmpty()) {
            JOptionPane.showMessageDialog(vistaIngreso, "Ingrese el dato particular");
        } else {
            ControladorIngreso.ingresoVehiculo(patente.getText(), Integer.parseInt(lugarTxt.getText()), tipoVehiculo.getSelectedItem().toString(), datoParticular.getText());
            ControladorListado.actualizarLista();
            ControladorLugares.ActualizarGrilla();
            VaciarTextFields();
        }

        //JOptionPane.showMessageDialog(this, "Llene todos los campos");
    }//GEN-LAST:event_aceptarActionPerformed

    private void datoParticularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datoParticularKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tipoVehiculo.getSelectedItem().toString().equals("Elegir opción...")) {
                labelError.setVisible(true);
            } else if (lugarTxt.getText().toString().equals("Elegir...")) {
                JOptionPane.showMessageDialog(vistaIngreso, "Elija un lugar para el vehículo");
            } else if (patente.getText().isEmpty()) {
                JOptionPane.showMessageDialog(vistaIngreso, "Ingrese una patente");
            } else if (datoParticular.getText().isEmpty()) {
                JOptionPane.showMessageDialog(vistaIngreso, "Ingrese el dato particular");
            } else {
                ControladorIngreso.ingresoVehiculo(patente.getText(), Integer.parseInt(lugarTxt.getText()), tipoVehiculo.getSelectedItem().toString(), datoParticular.getText());
                ControladorListado.actualizarLista();
                ControladorLugares.ActualizarGrilla();
                VaciarTextFields();
            }
        }
    }//GEN-LAST:event_datoParticularKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField datoParticular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDatoParticular;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel lugarTxt;
    private javax.swing.JTextField patente;
    private javax.swing.JComboBox<String> tipoVehiculo;
    // End of variables declaration//GEN-END:variables
}
