/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorInicio;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import modelo.Persona;

/**
 *
 * @author vales
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VistaInicio() {
        initComponents();
//        this.setLocationRelativeTo(VistaInicio.this);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("icono/images.png"));
        this.setIconImage(ico);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ingresoVehiculo = new javax.swing.JButton();
        retiroVehiculo = new javax.swing.JButton();
        listadoVehiculo = new javax.swing.JButton();
        labelEncargado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Vehículos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Estacionamiento El Parq");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de Vehículos"));
        jPanel1.setForeground(new java.awt.Color(18, 59, 102));
        jPanel1.setName(""); // NOI18N

        ingresoVehiculo.setBackground(new java.awt.Color(18, 59, 102));
        ingresoVehiculo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ingresoVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        ingresoVehiculo.setText("Ingreso de Vehículo");
        ingresoVehiculo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 59, 102), 2, true));
        ingresoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoVehiculoActionPerformed(evt);
            }
        });

        retiroVehiculo.setBackground(new java.awt.Color(18, 59, 102));
        retiroVehiculo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        retiroVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        retiroVehiculo.setText("Retiro de Vehículo");
        retiroVehiculo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 59, 102), 2, true));
        retiroVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiroVehiculoActionPerformed(evt);
            }
        });

        listadoVehiculo.setBackground(new java.awt.Color(18, 59, 102));
        listadoVehiculo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listadoVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        listadoVehiculo.setText("Listado de Vehículos");
        listadoVehiculo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 59, 102), 2, true));
        listadoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoVehiculoActionPerformed(evt);
            }
        });

        labelEncargado.setText("Encargado: ...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(listadoVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(retiroVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingresoVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(ingresoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(retiroVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listadoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoVehiculoActionPerformed
        ControladorInicio.botonIngreso();
    }//GEN-LAST:event_ingresoVehiculoActionPerformed

    private void listadoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoVehiculoActionPerformed
        ControladorInicio.botonListado();
    }//GEN-LAST:event_listadoVehiculoActionPerformed

    private void retiroVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiroVehiculoActionPerformed
        ControladorInicio.botonEgreso();
    }//GEN-LAST:event_retiroVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelEncargado;
    private javax.swing.JButton listadoVehiculo;
    private javax.swing.JButton retiroVehiculo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLabelEncargado() {
        return labelEncargado;
    }

    public void setLabelEncargado(javax.swing.JLabel labelEncargado) {
        this.labelEncargado = labelEncargado;
    }
}
